baseURL = "https://tamadalab.github.io/purplecat/"
languageCode = "en-us"
title = "purplecat"
theme = "cayman-hugo-theme"
enableEmoji = true
googleAnalytics = ""

pygmentsCodefences = true
pygmentsStyle = "pygments"

[params]
    project_name = "purplecat"
    project_tagline = "Purple cat, Purple cat, What do you see? I see the dependent libraries and their licenses"
    project_logo = "images/purplecat_128.png"
    dateFormat = "2006-01-02"

    footer = "[![GitHub](https://img.shields.io/badge/GitHub-tamadalab/purplecat-blueviolet.svg?logo=github)](https://github.com/tamadalab/purplecat) Made with [Hugo](https://gohugo.io/). Theme by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [GitHub Pages](https://pages.github.com/)."

    katex = true

[menu]
  [[menu.nav]]
    name = ":house: Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = ":anchor: How to Use"
    url = "/usage"
    weight = 2
  [[menu.nav]]
    name = ":smile: About"
    url = "/about"
    weight = 5

